### ISSUE TITLE
App rejected by iTunes Connect

### ISSUE THREAD

**Issue by ploddi** [spotxmobile/spotx-sdk-ios#4] opened 2015-11-14 08:59 UTC
```Missing load commands - The executable at '/Payload/AppodealSandbox.app/AdManagerAssets.bundle/AdManagerAssets' does not have the necessary load commands. Try rebuilding the app with the latest Xcode version. If you are using third party development tools, contact the provider.```

**Comment by lcniles** [comment] 2015-11-16 17:21
Thanks for the report; we're looking into this. Can you provide which version of Xcode you're using and which version of iOS you are targeting?

**Comment by dmitruss** [comment] 2015-11-16 17:46
ios 9.1
XCode 7.1

**Comment by lcniles** [comment] 2015-11-16 17:47
Thanks! Xcode 7.1 Beta or GA?

**Comment by dmitruss** [comment] 2015-11-16 18:13
RELEASE VERSION

**Comment by lcniles** [comment] 2015-12-03 19:57
Are you able to recreate this with SDK v2.1.1?

**Comment by dmitruss** [comment] 2015-12-04 08:16
version 2.1.1 has same problem.

**Comment by lcniles** [comment] 2015-12-04 16:04
I am curious what your linker command line looks like. Can you attach all of the build output?

**Comment by scottjulian** [comment] 2016-02-10 23:27
Has this been resolved @dmitruss ?

**Comment by dmitruss** [comment] 2016-02-11 14:15
i dont know, because we start use VPAID integration directrly

**Comment by lcniles** [comment] 2016-02-22 15:18
@dmitruss - I'm closing this issue as it appears you have taken an alternate approach. Feel free to re-open with some more information if this is not the case.

Thanks!

**Closed by lcniles** 2016-02-22 15:18 UTC

**Comment by lcniles** [comment] 2016-03-08 22:20
Update: With some help from Apple's Technical Support we uncovered the root cause here. The fix will be available as of v2.3 of our SDK.

Cheers!
